version: '3'
services:
  springboot-app:
    image: todo-app:latest
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://todoapp-mongodb-1:27017/todoapp
    depends_on:
      - todoapp-mongodb-1
      - keycloak
    networks:
      - my_network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: [ "start-dev" ]
    ports:
      - "8180:8080"
    networks:
      - my_network
    depends_on:
      - todoapp-mongodb-1

  todoapp-mongodb-1:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "27017:27017"
    command: --bind_ip 0.0.0.0
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my_network

networks:
  my_network:
    driver: bridge